{% set name = "hklpy" %}
{% set version = "1.0.0" %}
{% set sha256 = "061ad64f2f17144814d3f2a7db6b49df03015953749da02fc9564b3d6778eace" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36 or win or osx]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - hkl
    - numpy
    - ophyd
    - pint
    - pygobject
    - pyresttable

test:
  imports:
    - hkl
    - hkl.calc
    - hkl.context
    - hkl.diffract
    - hkl.engine
    - hkl.sample
    - hkl.util

about:
  home: https://github.com/bluesky/hklpy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Diffractometer computation library with ophyd pseudopositioner support
